services:
  - type: web
    name: fruit-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000 --server.address=0.0.0.0
    runtime: python-3.10
