services:
  - type: web
    name: fruit-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000 --server.address=0.0.0.0
    plan: free
