services:
  - type: web
    name: fruit-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000 --server.enableCORS=false
    pythonVersion: 3.9
